### ISSUE TITLE
commit code done so far on executor

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/quickfix-executor#1]
@MickMek can you please commit your current code into this repository  https://github.com/SSOC18/quickfix-executor/

**Comment by MickMek** [comment]
Unable to submit codes to this repository, as well as tradeclient's web UI, screenshots below:

<img width="961" alt="screen shot 2018-07-20 at 3 58 16 pm" src="https://user-images.githubusercontent.com/40487507/43003654-d91ab47e-8c35-11e8-8c70-52bf190514e5.png">

**Comment by shadiakiki1986** [comment]
Will see what I missed in the repository settings and get back to you

**Comment by shadiakiki1986** [comment]
please try again now

**Comment by shadiakiki1986** [comment]
done
