### ISSUE TITLE
screencast (~1h)

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/quickfix-executor#4]
Let's record a screencast showing the executor, tradeclient-web, tradeclient-console, wireshark in action.
Plenty of opensource software [on github](https://github.com/topics/screencast), e.g. https://getkap.co/ for mac or [peek](https://github.com/phw/peek)

Then let's upload it. We have several options
1. if it's a large file: youtube
2. if it's a small file: possibly after exporting it in gif format, we can just commit it into the repository here and include it in the readme. Check the `peek` repository above for an example

**Comment by shadiakiki1986** [comment]
any updates?

**Comment by MickMek** [comment]
just uploaded a mp4 screencast to the repository.
the gif file was much larger (151MB), and exceeded the Github's limit (25MB)

**Comment by shadiakiki1986** [comment]
Did you upload to youtube? Put a link to it from the readme

**Comment by MickMek** [comment]
done

**Comment by shadiakiki1986** [comment]
I just noticed that you uploaded the screencast to youtube AND to this repository.

The repository is only for source code, and *small* screencasts. (small ==   < 1 MB)

Please delete your commit 89c93a0 completely from git history. You will need something along the lines of [this](https://stackoverflow.com/questions/18010048/how-to-permanently-delete-a-commit-from-gits-history)

**Comment by shadiakiki1986** [comment]
This seems to be fixed. Can you confirm so I close this issue?

**Comment by MickMek** [comment]
yes fixed
